language: php
dist: xenial
php:
    - '7.2'
before_script:
    - cd src/php
    - composer install
    - nvm install 9.4
    - npm install
    - cd ../js
    - npm -g install snyk
    - npm install
    - cd ../php
script:
    - vendor/bin/phpunit --bootstrap ../../test/php/bootstrap.php -c ../../test/php/phpunit.xml
    - vendor/bin/phpstan analyse Chaplin
    - vendor/bin/phpcs
    - npm test
    - cd ../js
    - npm test
